[theme]
primaryColor = "#6200EA"               # Purple
backgroundColor = "#FFFFFF"            # White
secondaryBackgroundColor = "#F0F2F6"   # Light Gray
textColor = "#000000"                  # Black
font = "sans serif"
